"""Google Drive Automatic Sync Module for OneDrama Engine.

Automatically exports finished master movies and YouTube viral metadata packages
directly to Google Drive for Desktop ('G:\\My Drive\\OneDrama_Uploads\\').

When files are placed into this folder, Google Drive Desktop automatically
syncs them to your cloud Google Drive in the background.
"""

from __future__ import annotations

import datetime
import os
import re
import shutil
import string
import sys
from typing import Any, Optional

from modules import log, read_json


def find_google_drive_root(custom_path: Optional[str] = None) -> Optional[str]:
    """Auto-detects the local Google Drive for Desktop mount point."""
    if custom_path and os.path.isdir(custom_path):
        return custom_path

    # Common Windows drive letters used by Google Drive for Desktop
    # Primary: G:\My Drive or G:\
    potential_roots = [
        r"G:\My Drive",
        r"G:\\",
        r"H:\My Drive",
        r"H:\\",
        os.path.expanduser(r"~\Google Drive\My Drive"),
        os.path.expanduser(r"~\Google Drive"),
    ]

    for p in potential_roots:
        if os.path.isdir(p):
            # If it's G:\ and has 'My Drive' inside, prefer 'My Drive'
            sub_my_drive = os.path.join(p, "My Drive")
            if os.path.isdir(sub_my_drive):
                return sub_my_drive
            return p

    # Probe all existing drive letters for 'My Drive'
    available_drives = [f"{d}:\\" for d in string.ascii_uppercase if os.path.exists(f"{d}:\\")]
    for d in available_drives:
        my_drive_candidate = os.path.join(d, "My Drive")
        if os.path.isdir(my_drive_candidate):
            return my_drive_candidate

    return None


def format_viral_metadata_text(
    guide_path: str, json_pkg_path: Optional[str] = None
) -> str:
    """Generates a clean, copy-paste ready text file for YouTube Studio."""
    guide_text = ""
    if os.path.isfile(guide_path):
        try:
            with open(guide_path, "r", encoding="utf-8") as f:
                guide_text = f.read()
        except Exception:
            guide_text = ""

    pkg_data = read_json(json_pkg_path, default={}) if json_pkg_path and os.path.isfile(json_pkg_path) else {}

    # Extract components if json exists, else fallback to guide_text
    titles = pkg_data.get("titles", [])
    description = pkg_data.get("description", "")
    tags = pkg_data.get("tags", [])
    hashtags = pkg_data.get("hashtags", ["#manhuarecap", "#hindidubbed", "#donghua"])
    timestamps = pkg_data.get("timestamps", [])
    disclaimer = pkg_data.get("fair_use_disclaimer", "")
    mj_prompt = pkg_data.get("midjourney_prompt", "")
    badge = pkg_data.get("thumbnail_badge", "MAX LEVEL GOD!")
    char_profile = pkg_data.get("main_character_profile", {})

    output_lines = [
        "================================================================================",
        "🎬 YOUTUBE VIRAL PUBLISHING PACKAGE (COPY-PASTE READY)",
        f"📅 Generated by OneDrama Studio on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "================================================================================",
        "",
        "--------------------------------------------------------------------------------",
        "📌 5 HIGH-CTR VIRAL TITLES (Select your favorite):",
        "--------------------------------------------------------------------------------",
    ]

    if titles:
        for idx, t in enumerate(titles, 1):
            output_lines.append(f"Option {idx}: {t}")
    else:
        output_lines.append("Option 1: [Hindi] Betrayed By His Clan, But Reincarnated With A God-Tier System! | Full Manhua Recap")
        output_lines.append("Option 2: He Was Called Trash, Until He Unlocked The Ancient Dragon Emperor Powers!")
        output_lines.append("Option 3: 100 Hours In Another World: From Weakling To Undefeated Celestial Overlord!")

    output_lines.extend([
        "",
        "--------------------------------------------------------------------------------",
        "📝 YOUTUBE DESCRIPTION BOX (Copy & paste everything below into Description):",
        "--------------------------------------------------------------------------------",
        description if description else "In a cruel world where strength dictates fate, an outcast awakens a legendary power and embarks on a relentless path of revenge and dominance.",
        "",
        "⏱️ VIDEO CHAPTERS & TIMESTAMPS:",
    ])

    if timestamps:
        for ts in timestamps:
            output_lines.append(f"{ts.get('time', '0:00:00')} - {ts.get('title', 'Chapter')}")
    else:
        output_lines.append("0:00:00 - Episode 1: The Mountain Trial")

    output_lines.extend([
        "",
        "⚖️ FAIR USE LEGAL DISCLAIMER:",
        disclaimer if disclaimer else (
            "Copyright Disclaimer Under Section 107 of the Copyright Act 1976, allowance is made "
            "for 'fair use' for purposes such as criticism, comment, news reporting, teaching, "
            "scholarship, and research. This video is a transformative recap with original commentary and voiceover."
        ),
        "",
        "🏷️ HASHTAGS:",
        " ".join(hashtags if hashtags else ["#manhuarecap", "#hindidubbed", "#donghua"]),
        "",
        "--------------------------------------------------------------------------------",
        "🏷️ YOUTUBE TAGS (Copy & paste directly into YouTube Studio Tags box):",
        "--------------------------------------------------------------------------------",
        ", ".join(tags) if tags else "manhua recap, hindi dubbed, anime explained in hindi, full manhwa movie",
        "",
        "--------------------------------------------------------------------------------",
        "🖼️ MIDJOURNEY v6 / FLUX.1 MASTER THUMBNAIL PROMPT:",
        "--------------------------------------------------------------------------------",
    ])

    if char_profile:
        output_lines.append(f"• Character: {char_profile.get('name', 'Protagonist')}")
        output_lines.append(f"• Appearance: {char_profile.get('appearance', 'Handsome cultivator, golden eyes')}")
        output_lines.append(f"• Weapon/Attire: {char_profile.get('weapon', 'Flaming sword')} / {char_profile.get('attire', 'Battle robes')}")
        output_lines.append("")

    output_lines.extend([
        "Copy-Paste Prompt for Midjourney / Flux.1:",
        mj_prompt if mj_prompt else (
            "Cinematic anime manhua style, dynamic low-angle camera, handsome male cultivator with glowing "
            "golden eyes holding a celestial flaming sword, epic battle background with stormy skies and lightning, "
            "hyper-detailed, vibrant lighting, masterpiece --ar 16:9 --v 6.0"
        ),
        "",
        f"🔤 RECOMMENDED THUMBNAIL TEXT BADGE: \"{badge}\"",
        "(Place in bold, high-contrast yellow/red font with black stroke on the top-left corner)",
        "",
        "================================================================================",
        "✅ End of Package - Upload your video & paste these metadata to maximize CTR & Views!",
        "================================================================================",
    ])

    # If guide_text has more raw context, append
    if not pkg_data and guide_text:
        return guide_text

    return "\n".join(output_lines)


def copy_file_with_progress(src: str, dst: str, buffer_size: int = 16 * 1024 * 1024) -> None:
    """Copies large video files with a safe buffer."""
    total_bytes = os.path.getsize(src)
    copied = 0

    with open(src, "rb") as fsrc, open(dst, "wb") as fdst:
        while True:
            buf = fsrc.read(buffer_size)
            if not buf:
                break
            fdst.write(buf)
            copied += len(buf)


def sync_to_google_drive(
    movie_path: str,
    guide_path: str,
    json_pkg_path: Optional[str] = None,
    series_title: Optional[str] = None,
    destination_folder_name: str = "OneDrama_Uploads",
    custom_drive_path: Optional[str] = None,
) -> Optional[str]:
    """Syncs the final compilation movie and YouTube viral package to Google Drive.

    Returns the path to the created Google Drive folder, or None if drive is not found.
    """
    gdrive_root = find_google_drive_root(custom_drive_path)
    if not gdrive_root:
        log.warning("Google Drive for Desktop mount not found. Skipping Google Drive sync.")
        return None

    if not os.path.isfile(movie_path):
        log.error("Movie file does not exist for Google Drive export: %s", movie_path)
        return None

    # Determine project folder name
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    if series_title:
        clean_title = re.sub(r'[\\/*?:"<>|]', "", series_title).strip().replace(" ", "_")
        folder_name = f"{date_str}_{clean_title}"
    else:
        movie_stem = os.path.splitext(os.path.basename(movie_path))[0]
        folder_name = f"{date_str}_{movie_stem}"

    dest_folder = os.path.join(gdrive_root, destination_folder_name, folder_name)
    os.makedirs(dest_folder, exist_ok=True)

    log.info("Google Drive detected at '%s'", gdrive_root)
    log.info("Syncing master package to Google Drive folder: '%s'", dest_folder)

    # 1. Copy master video file
    dest_movie_path = os.path.join(dest_folder, os.path.basename(movie_path))
    movie_size_mb = round(os.path.getsize(movie_path) / (1024 * 1024), 2)
    log.info("  -> Copying movie (%s MB) to Google Drive...", movie_size_mb)
    copy_file_with_progress(movie_path, dest_movie_path)

    # 2. Generate and write formatted viral metadata text file
    viral_metadata_text = format_viral_metadata_text(guide_path, json_pkg_path)
    dest_txt_path = os.path.join(dest_folder, "YOUTUBE_VIRAL_PACKAGE.txt")
    with open(dest_txt_path, "w", encoding="utf-8") as f:
        f.write(viral_metadata_text)
    log.info("  -> Created viral YouTube metadata package: 'YOUTUBE_VIRAL_PACKAGE.txt'")

    # 3. Also copy raw JSON package if present
    if json_pkg_path and os.path.isfile(json_pkg_path):
        dest_json_path = os.path.join(dest_folder, "youtube_package.json")
        shutil.copy2(json_pkg_path, dest_json_path)

    log.info("Google Drive export complete! Files will auto-sync to cloud via Google Drive Desktop.")
    return dest_folder
